# BoyCtrl配置文件，需要放在dll同目录，文件编码utf-8
# #开头的行为注释
# 设置值为1表示启用，为0表示不启用

# 是否使用独立通道朗读，对应朗读接口的withSlave参数
speak.useSlave = 1

# 朗读通道名称，仅当speak.useSlave = 1时生效
# 读屏三方通道列表中必须存在该通道，否则使用共享三方通道朗读
speak.slaveName = 我的三方通道

# 是否排队朗读，对应朗读接口的append参数
speak.append = 0

# 朗读过程中是否允许被打断，对应朗读接口的allowBreak参数
speak.allowBreak = 1

# 是否启用任意键打断，相当于调用BoyCtrlSetAnyKeyStopSpeaking接口
anyKeyBreak = 0

# 日志文件路径，可由初始化接口参数覆盖
logPath = 